User/urls.py
from django.urls import path
from User.views import signup_view,login_view,logout_view

app_name = "user"
urlpatterns = [
    path('signup/', signup_view , name='signup'),
    path('login/',login_view , name= 'login'),
    path('logout/',logout_view , name= 'logout'),
]

deskripsi/urls.py
from django.urls import path, include
from deskripsi.views import detail_barang, beli_barang, barang_terbeli, get_JSON_daftar_barangterbeli

app_name = 'deskripsi'

urlpatterns = [
    path("konfirmasi/<slug_barang>/" , beli_barang , name= 'barangbeli'),
    path('semuabarangdibeli/' , barang_terbeli , name='barangterbeli'),
    path("<slug_barang>/" , detail_barang , name= 'barangdetail'),
    path('caribarangterbeli/<str:value>/' , get_JSON_daftar_barangterbeli , name = "daftar_barangterbeli"),
]

tkppw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('Barang.urls', namespace="barang")),
    path('subscriber/',include('subscribe.urls')),
	path("review/", include('homepage.urls')), 
    path("deskripsi/" , include('deskripsi.urls')),
    path('user/',include('User.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT )
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

deskripsi/models.py
from django.db import models
from Barang.models import BarangModel


# Create your models here.
class BarangPembeli(models.Model):
    barang = models.ForeignKey(BarangModel,on_delete=models.CASCADE)
    def __str__(self):
        return self.barang

deskripsi/views.py
from django.shortcuts import render,redirect,HttpResponseRedirect,HttpResponse
from Barang.forms import BarangForm
from Barang.models import BarangModel
from deskripsi.models import BarangPembeli
from django.http import JsonResponse

from django.conf import settings
from django.contrib.auth.decorators import login_required

def detail_barang(request,slug_barang):    
    barang_detail = BarangModel.objects.get(slug = slug_barang)
    return render(request, 'deskripsi/deskripsi_barang.html',{
        "barang":barang_detail,
 })

@login_required
def beli_barang(request , slug_barang):
    barangnya_dibeli = BarangModel.objects.get(slug=slug_barang )
    barangnya_dibeli.terbeli = True
    barang_terbeli = BarangPembeli(barang = barangnya_dibeli)
    barang_terbeli.save()
    barangnya_dibeli.save()
    return redirect('/')

def barang_terbeli(request):
    barang_dibeli_pengunjung = BarangModel.objects.filter(terbeli=True)
    print(barang_dibeli_pengunjung)
    return render(request , 'deskripsi/barangterbeli.html' , {"barangkebeli" : barang_dibeli_pengunjung,} )

def get_JSON_daftar_barangterbeli(request,value):
    result = list(BarangModel.objects.filter(nama_barang__icontains=value).values())
    return JsonResponse({"data": result})

templates/deskripsi/barangterbeli.html
{% extends 'base.html' %}
{% load static %}


{% block body %}


<div class="container" style="margin: 35px;">
    <h1>Barang Terbeli</h1>
    <div class="box-search" style="margin: 60px;">
        <form class="search-form" onsubmit="return caribarangterbeli();" action='#'>
            <input type="text" placeholder="Search by Products Name" id="search">
            <button type="submit" id="button-search"><i class="fa fa-search"></i></button>
        </form>
    </div>
    <div class="row" id="daftarbarangkebeli">
        {% for barang in barangkebeli  %}
        <div class="col-md-6">
            <img src="{{ barang.picture.url }}" alt="" class='image-product'>
        </div>
        <div class="col-md-6">
           <p class="brand-barang"> {{ barang.brand_barang }} </p>
            <p class='nama-barang'> {{ barang.nama_barang }} </p>
            <p class="price-barang"> Rp {{ barang.harga }} </p>
        </div>
        {% endfor %}
    </div>
</div>

<script src="{% static 'js/deskripsi.js' %}"></script>

{% endblock %}

templates/deskripsi/deskripsi_barang.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
<div class="switch" style="margin: 25px;">Switch Theme?              
    <span class="inner-switch">OFF</span>
</div>

<div class="container" style="margin-top: 60px; margin-bottom: 100px;">
    <div id="div1">
        <h1>Barang Terbeli</h1>
    </div>
    <div class="row">
        <div class="col-md-6">
            <img src="{{ barang.picture.url }}" alt="" class='image-product'>
        </div>
        <div class="col-md-6">
            <p class="brand-barang"> {{ barang.brand_barang }} </p>
            <p class='nama-barang'> {{ barang.nama_barang }} </p>
            <p class="price-barang"> Rp {{ barang.harga }} </p>
            {% if user.is_authenticated %}
            <form action="{% url 'deskripsi:barangbeli' barang.slug  %}" enctype="multipart/form-data">   
                <button type="submit" class="btn btn-submit btn-lg mt-4 ">BUY NOW</button> 
            </form>
            {% else %}
            <div class="popup">
                <p>! you need to sign in to buy this product !</p>
            </div>
            {% endif %}
        </div>
    </div>
</div>

<script src="{% static 'js/deskripsi.js' %}"></script>
{% endblock body %}