Barang/urls.py
from django.urls import path, include
from . import views

app_name = 'barang'
urlpatterns = [
    path('barang/', views.createBarang , name ='createbarang'),
    path('', views.homepage , name = 'homepage'),
    path('daftar_barang/<str:value>' , views.get_JSON_daftar_barang , name = "daftar_barang")
]

User/urls.py
from django.urls import path
from User.views import signup_view,login_view,logout_view

app_name = "user"
urlpatterns = [
    path('signup/', signup_view , name='signup'),
    path('login/',login_view , name= 'login'),
    path('logout/',logout_view , name= 'logout'),
]

deskripsi/urls.py
from django.urls import path, include
from deskripsi.views import detail_barang, beli_barang, barang_terbeli, get_JSON_daftar_barangterbeli

app_name = 'deskripsi'

urlpatterns = [
    path("konfirmasi/<slug_barang>/" , beli_barang , name= 'barangbeli'),
    path('semuabarangdibeli/' , barang_terbeli , name='barangterbeli'),
    path("<slug_barang>/" , detail_barang , name= 'barangdetail'),
    path('caribarangterbeli/<str:value>/' , get_JSON_daftar_barangterbeli , name = "daftar_barangterbeli"),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.review_create, name='review_create'),
    path('daftar_review/<str:value>/' , views.get_JSON_daftar_review , name = "daftar_review")
]

subscribe/urls.py
from django.urls import path
from . import views

app_name = 'subscribe'
urlpatterns = [
    path('subscriber_create/',views.subscriber_create,name='subscriber_create'),
    path('subscriber/',views.subscriber,name='subscriber'),
    path('faq/', views.faq, name='faq'),
    path('notAuth/', views.notAuth, name='notAuth'),
    path('daftar_subscriber/<str:value>' , views.get_JSON_daftar_subscriber , name = "daftar_subscriber")
]

tkppw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('Barang.urls', namespace="barang")),
    path('subscriber/',include('subscribe.urls')),
	path("review/", include('homepage.urls')), 
    path("deskripsi/" , include('deskripsi.urls')),
    path('user/',include('User.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT )
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/homepage.css' %}">
    <link rel="stylesheet" href="{% static 'css/buatbarang.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/input.css' %}">
    <link rel="stylesheet" href="{% static 'css/deskripsi.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <link rel="stylesheet" href="{% static 'css/faqcss.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Sanchez&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Tenor+Sans&display=swap" rel="stylesheet">
    {% block title %}


    {% endblock %}
</head>
<body style="font-family: Sanchez;">
    <nav class="navbar navbar-expand-lg navbar-light bg-white sticky-top">
        <a href="{% url 'barang:homepage' %}" class="navbar-brand">
            <img src="https://i.ibb.co/y0QH6Dw/Group-1.jpg" width="234px" height="52px" alt="">
        </a>
        <button class="navbar-toggler navbar-light bg-light" data-toggle="collapse" data-target="#navbarMenu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarMenu">
            <ul class="navbar-nav mr-auto ml-auto">
                <li class="nav-item">
                    <a href="{% url 'barang:homepage' %}" class="nav-link">Products</a>
                </li>
                <li class="nav-item">
                    <a href="#about-me" class="nav-link">About</a>
                </li>
                <li class="nav-item">
                    <a href="#contact" class="nav-link">Contact</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'barang:createbarang' %}" class="nav-link">Create Barang</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'homepage:review_create' %}" class="nav-link">Review</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'subscribe:subscriber' %}" class="nav-link">Subscriber</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <form action="{% url 'user:logout' %}" method="POST" style="display: inline;">
                        {% csrf_token %}
                        <button type='submit' style="background-color: #B09586; border: #B09586;"
                            class="btn btn-danger btn-lg mr-3" name='logout-btn'>Logout</button>
                    </form>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a href="{% url 'user:login' %}" class="nav-link">
                        <img src="https://i.ibb.co/yPYKM8Q/account-1.jpg" width="36px" height="38px" alt="">
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'deskripsi:barangterbeli' %}" class="nav-link">
                        <img src="https://i.ibb.co/xFz9HJS/cart-1.jpg" width="50px" height="46px" alt="">
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <script src="{% static 'js/faq.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="//code.j query.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <script src="{% static 'js/review.js' %}" type="text/javascript"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">

    {% block body %}


    {% endblock body %}

    <footer id='contact' class="section footer-classic context-dark bg-image" style="background: #575757; padding: 2em;">
        <div class="container">
            <div class="row row-50">
                <div class="col-md-6">
                    <h5>Contacts</h5>
                    <dl class="contact-list">
                        <dt>Address:</dt>
                        <dd> University of Indonesia</dd>
                    </dl>
                    <dl class="contact-list">
                        <dt>email:</dt>
                        <dd><a href="mailto:#">keruface@gmail.com</a></dd>
                    </dl>
                    <dl class="contact-list">
                        <dt>phones:</dt>
                        <dd><a href="tel:#">+628951052</a> <span>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6 col-xl-5">
                    <p>We are an dedicated website for selling trusted skincare product for your daily uses.</p>
                    <!-- Rights-->
                    <p class="rights"><span>©</span>
                        <span class="copyright-year">2019</span><span>Keruface</span><span>. </span><span>All
                            Rights Reserved.</span></p>
                </div>
            </div>
        </div>
    </footer>


    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>
    <script src="{% static 'js/deskripsi.js' %}"></script>
    <script src='{% static "js/homepage.js" %}' type="text/javascript"></script> 
    <script src="{% static 'js/create_barang.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
</body>

</html>

templates/faq.html
{% extends "base.html" %}
{% load static %}

    
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <script src="{% static 'js/faq.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/faqcss.css' %}">
    

{% block body %}

{% block title %}
<title>FAQ</title>

{% endblock %}


<body style="background-color:whitesmoke">

<div id = "div1" class="display-4 p-3 mb-4 text-center" style="font-family: 'Playfair Display'; ">FAQ Section</div>

<img id = "img1" style = "margin-left: 39vw" src="{% static 'img/what.png'%}" width="300">

<div class="row"></div>
<div class="row">
    <div class="col-4"></div>
    <div class="col-4 row-mar">
        <div id="jQuery_accordion">
            <h3>What is KERUFACE?</h3>
                <p class="text-style">
                    Keruface is a platform that provides<br>
                    variety of skincare products, specially<br>
                    picked for any skin type and your budget</p>
            
            <h3>How do i know about what products do i need?</h3>
                <p class="text-style">
                    We will give you our best product<br>
                    recommendation. You just need to tell<br>
                    us about your skin condition by filling the<br>
                    form we provide !
                </p>
            
            <h3>Is this website reliable?</h3>
                <p class="text-style"> 
                    Ofcourse we do. Let's check out<br>
                    the review from our beloved customer
                </p>
          </div>
      </div>
    </div>

</body>


{% endblock %}

templates/input.html
{% extends "base.html" %}
    {% block title %}
        <title>Tell Us Your Thoughts!</title>
    {% endblock %}
{% block body %}
{% load static%}


{% if user.is_authenticated %}
<div id="div1" class="display-4 p-3 mb-4 text-center" style="font-family: 'Playfair Display';">Tell Us Your Thoughts!</div>
<div  style="font-family: 'Playfair Display';" class="switch ml-4">Change theme:             
    <span class="inner-switch 1">OFF</span>
</div>

<div class="box-search">
    <form class="search-form" onsubmit="return carireview();" action='#'>
        <input type="text" placeholder="Search by Products Name" id="search">
        <button type="submit" id="button-search"><i class="fa fa-search"></i></button>
    </form>
</div>
<br>

<div class="container" style="width: 900px;">
    <div class="row" id="barang">
        {% for review in reviews %}
            <div class="card mb-1 tor" style="width: 282px; margin-left: 3px; margin-right: 3px;">
                <div class="card-body">
                <h5 class="card-title">{{ review.name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">testimoni</h6>
                <p class="card-text">{{ review.fill }}</p>
                </div>
            </div> 
        {% endfor %}
    </div>
</div>
    <br>
    <br>
    <br>
    <div class="h2 p-3 mb-4 text-center" style="font-family: 'Playfair Display';">Submit Your Responses!</div>
    <form class="css" action="{% url 'homepage:review_create' %}" method="post" style="font-family: 'Playfair Display'">
        {% csrf_token %}
            <div class="form-row">
                <div class="col-lg-2"></div>
                    <div class="form-group col-lg-8 tag">
                        
                        {% for fields in form %}
                            <br>
                            {{ fields.label_tag }} 
                            {{ fields }}
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-2"></div>
                <br>
            <div class="form-row">
            
                <input type="submit" class="btn mr-auto ml-auto" value="Submit!" style="background-color:#B09586; color: white;">
            </div>
    </form>
    <br>
    <br>
    <br>
    {% else %}
    <div id="div1" class="display-4 p-3 mb-4 text-center" style="font-family: 'Playfair Display';">Please login first!</div>
    {% endif %}
{% endblock %}

templates/koran.html
{% extends "base.html" %}
{% load static %}


{% block body %}

{% block title %}
<title>Keep in Touch with Us!</title>
{% endblock %}

<form class="css" action="{% url 'subscribe:subscriber_create' %}" method="post">
        <div class="display-4 p-3 mb-4 text-center" style="font-family: 'Playfair Display';">Keep in Touch with Us!</div>
    {% csrf_token %}
    <div class="form-row">
        <div class="col-sm-3"></div>
        <div class="form-group col-sm-6">
            {% for fields in form %}
                <br>
                {{ fields.label_tag }}
                <br>
                {{ fields }}
            {% endfor %}
        </div>
        <div class="col-sm-3"></div>

    </div>
    <div class="form-row">
        <!-- <div class="col-sm-3"></div> -->
        <div class="text-center col-sm-5">
        <input type="submit" class="btn mx-auto my-auto btn-submit:hover btn-submit float-right text" value="Subscribe">
    </div>
    </form>
{% endblock %}

templates/not.html
{% extends "base.html" %}
{% load static %}


{% block body %}

{% block title %}
<title>Keep in Touch with Us!</title>
{% endblock %}

<div class="display-4 p-3 mb-4 text-center" style="font-family: 'Playfair Display'; margin-top: 30vh;">Please sign in first.</div>

{% endblock %}

templates/subscriber.html
{% extends "base.html" %}
{% load static %}


{% block body %}

{% block title %}
<title>Keep in Touch with Us!</title>
{% endblock %}

      <div class="display-4 p-3 mb-4 text-center" style="font-family: 'Playfair Display';">Subscriber</div>
      <div class="article">
          <a href="{% url 'subscribe:subscriber' %}"></a>
          <div class="article">
              <div class="row" id='subscriber'>
                  <!-- {% for subscriber in subscribers %}
                      <div class="col-sm-3 text-center" style= "font-family: 'Playfair Display';">
                          <h2>{{ subscriber.name }}</h2>
                      </div>
                  {% endfor %} -->
              </div>
          </div>
      </div>
          <br>
            <div class = 'form-group text-center col-md-9'>
                {% if user.is_authenticated %}
                <a href="{% url 'subscribe:subscriber_create' %}"><button type="button" class= "btn btn-secondary btn-submit btn-submit:hover btn-lg btn-sm">Subscribe Here!</button></a>
                {% else %}
                <a href="{% url 'subscribe:notAuth' %}"><button type="button" class= "btn btn-secondary btn-submit btn-submit:hover btn-lg btn-sm">Subscribe Here!</button></a>
                {% endif %}
                      
      </div>
      <div class = "container ">
        <div class = 'form-group text-center col-md-9' style="margin-left:5vw">
            <a href="{% url 'subscribe:faq' %}"><button type="button" class= "btn btn-secondary btn-submit btn-submit:hover btn-lg btn-sm">FAQ</button></a>
        </div>
  </div>
      <div class="display-3 text-center mb-4 p-1 mt-4">Find my name</div>
    <div class="box-search">
        <form class="search-form p-3" onsubmit="return cariSubscriber();" action='#'>
            <input type="text" placeholder="Find your name here!" id="search">
            <button type="submit" id="button-search"><i class="fa fa-search"></i></button>
        </form>
    </div>

  </div>
  <br>
  <br>

  
  {% endblock %}
  