User/urls.py
from django.urls import path
from User.views import signup_view,login_view,logout_view

app_name = "user"
urlpatterns = [
    path('signup/', signup_view , name='signup'),
    path('login/',login_view , name= 'login'),
    path('logout/',logout_view , name= 'logout'),
]

tkppw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('Barang.urls', namespace="barang")),
    path('subscriber/',include('subscribe.urls')),
	path("review/", include('homepage.urls')), 
    path("deskripsi/" , include('deskripsi.urls')),
    path('user/',include('User.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT )
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

User/models.py
from django.db import models

# Create your models here.

User/forms.py
from django.contrib.auth import password_validation
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from django.contrib.auth.models import User
from django.forms import CharField
from django.forms.widgets import PasswordInput, TextInput
from django.utils.translation import gettext, gettext_lazy as _



class UserCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

    password1 = CharField(
        label=_("Password"),
        strip=False,
        widget=PasswordInput(attrs={
            'class': 'form-control',
           'style': 'border: black solid px'
        }),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = CharField(
        label=_("Password confirmation"),
        widget=PasswordInput(attrs={
            'class': 'form-control',
            'style': 'border: black solid 1px'
        }),
        strip=False,
        help_text=_("Please enter the same password"),
    )

    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}
        widgets = {
            'username': TextInput(attrs={
        'class': 'form-control',
        'style': 'border: black solid 1px'})
        }
        labels = {
            'username':_("Username")
        }
        
class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = UsernameField(widget=TextInput(attrs={
        'class': 'form-control',
        'style': 'border: black solid 1px'}))
    password = CharField(
        label=_("Password"),
        strip=False,
        widget=PasswordInput(attrs={
            'class': 'form-control',
            'style': 'border: black solid 1px'
        }),
    )
from django.contrib.auth import password_validation
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from django.contrib.auth.models import User
from django.forms import CharField
from django.forms.widgets import PasswordInput, TextInput
from django.utils.translation import gettext, gettext_lazy as _



class UserCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

    password1 = CharField(
        label=_("Password"),
        strip=False,
        widget=PasswordInput(attrs={
            'class': 'form-control',
           'style': 'border: #B09586 solid 1px'
        }),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = CharField(
        label=_("Password confirmation"),
        widget=PasswordInput(attrs={
            'class': 'form-control',
            'style': 'border: #B09586 solid 1px'
        }),
        strip=False,
        help_text=_("Please enter the same password"),
    )

    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}
        widgets = {
            'username': TextInput(attrs={
        'class': 'form-control',
        'style': 'border: #B09586 solid 1px'})
        }
        labels = {
            'username':_("Username")
        }
        
class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = UsernameField(widget=TextInput(attrs={
        'class': 'form-control',
        'style': 'border: #B09586 solid 1px'}))
    password = CharField(
        label=_("Password"),
        strip=False,
        widget=PasswordInput(attrs={
            'class': 'form-control',
            'style': 'border: #B09586 solid 1px'
        }),
    )

User/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout
from User.forms import UserCreateForm,UserLoginForm

# Create your views here.
def signup_view(request):
    if request.user.is_authenticated:
        return redirect('/')
    else: 
        form = UserCreateForm()
        if request.method == "POST":
            form = UserCreateForm(data=request.POST)
            if form.is_valid():
                user = form.save()
                login(request,user)
                return redirect('/')
        return render(request , "User/signup.html" , {"form": form})

def login_view(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        form_login = UserLoginForm()
        if request.method == "POST":
            form_login = UserLoginForm(request=request, data= request.POST)
            if form_login.is_valid():   
                user = form_login.get_user()
                login(request,user=user)
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))   
                return redirect('/')
            else:
                return render (request, 'User/login.html', context={'form': form_login,'error':form_login.get_invalid_login_error()})
        return render(request , 'User/login.html', {"form":form_login})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('barang:homepage')
    return HttpResponse()

templates/User/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title> Log In |  Keruface </title>
{% endblock %}

{% block body %}

    <div class="container" style="transform: translateY(30%); font-family: Sanchez; margin-bottom: 20em;">
        <div class="row" style="justify-content: center; align-items: center; display: flex; flex-direction: column; ">
            <div style="padding: 8em; border: 3px solid #B09586;">
                <div class="display-3 text-center mb-4"> Log In </div>
                <form action="{% url 'user:login' %}" method="POST">
                    {% csrf_token %}
                    {% for error_message in error %}
                    <p style="font-size: 1.2em">*{{ error_message }}</p>
                    {% endfor %}
                    {% for fields in form %}
                    <div class="form-group">
                        <h5 class="text-center">{{ fields.label }}</h5>
                        {{ fields }}
                    </div>
                    {% endfor %}
                    {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                    {% endif %}
                    <div class="row justify-content-center mt-4">
                        <input type="submit" style="background-color:#B09586; border: #B09586;" class="btn btn-success btn-lg col-5 mt-4" value='Login' name="login-btn">
                        <p class='col-7 mt-4'><a href="{% url 'user:signup' %}" style="color: black; font-size: 1.2em;"> Doesn't Have an Account? </a> </p>
                    </div>    
                </form>
            </div>
        </div>
    </div>
    
{% endblock %}
    

templates/User/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title %}

<title> Create User |  Keruface </title>

{% endblock %}

{% block body %}

    <div class="container" style="transform: translateY(30%); font-family: Sanchez; margin-bottom: 20em;">
    <div class="row" style="justify-content: center; align-items: center; display: flex; flex-direction: column;">
        <div style="padding: 8em; border: 3px solid #B09586;">
            <div class="display-3 mb-4 text-center">Sign Up</div>
                <form action="{% url 'user:signup' %}" method="POST">
                    {% csrf_token %}
                    {% for fields in form %}
                    <div class="form-group">
                            {% for error in fields.errors %}
                                <p style="font-size: 1.2em">*{{ error }}</p>
                            {% endfor %}
                            <h5 class="text-center">{{ fields.label }}</h5>
                            {{ fields }}
                        </div>
                    {% endfor %}
                    <div class="text-center">
                    <input type="submit" value='Sign Up' class="btn btn-success btn-lg mt-4" style="background-color:#B09586; border: #B09586;">
                </form>
        </div>
    </div>    
    </div>    
</div>
    
{% endblock %}
    